main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: '1.20'
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.21"
commands:
  profile:
    description: Profile command
  necronomicon:
    description: Main command